/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package grimsi.accservermanager.backend.api;

import grimsi.accservermanager.backend.dto.ErrorDto;
import grimsi.accservermanager.backend.dto.SysteminfoDto;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "grimsi.accservermanager.backend.codegen.v3.generators.java.SpringCodegen", date = "2019-03-10T17:37:16.729Z[GMT]")
@Api(value = "info", description = "the info API")
public interface InfoApi {

    @ApiOperation(value = "Get information about the system", nickname = "getInfo", notes = "", response = SysteminfoDto.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Expected response to a valid request", response = SysteminfoDto.class),
        @ApiResponse(code = 200, message = "unexpected error", response = ErrorDto.class) })
    @RequestMapping(value = "/info",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<SysteminfoDto> getInfo();

}
